tag:
  - norec_sentence_nob
  - norec_sentence_nob_mcf
task: norec_sentence_nob_mcf_p0
include: _norec_sentence_nob_yaml
doc_to_text: "Tekst: {{review}}\nEr sentimentet A. negativ eller B. positiv?\nSvar:"
doc_to_choice: !function utils.choices_letters
process_results: !function utils.process_results_mcf
