tag:
  - slide_nob_nno_swe_dan
  - slide_nob_nno_swe_dan_hybrid
task: slide_nob_nno_swe_dan_hybrid_p0
include: _slide_nob_nno_swe_dan_yaml
doc_to_text: "Hvilket språk er det i følgende setning?\n{{text}}\nEr det bokmål, nynorsk, dansk, svensk, eller et annet språk?\nSvar:"
doc_to_choice: !function utils.choices_words
