tag:
  - norbelebele_nob
  - norbelebele_nob_mcf
task: norbelebele_nob_mcf_p2
include: _norbelebele_nob_yaml
doc_to_text: "{{question}}\nHvilket av følgende mulige svar er det riktige?\n A: {{mc_answer1}}\n B: {{mc_answer2}}\n C: {{mc_answer3}}\n D: {{mc_answer4}}\nSvar:"
doc_to_choice: !function utils.choices_letters
process_results: !function utils.process_results_mcf
